// DeveloperTerms.swift
// VocaMac
//
// A built-in Dictionary pack: the English terms Israeli developers say with a
// Hebrew accent inside Hebrew sentences — קומיט, פוש, פול ריקווסט, קלוד אמדי —
// mapped to how they are actually written. Applied by DictionaryService after
// transcription like any user entry, so "אחרי הקומיט תעשה פוש" comes out as
// "אחרי ה־commit תעשה push". Everything here is an ordinary DictionaryEntry
// once added: editable, deletable, exportable.
//
// Curation rule: a trigger must be a transliteration nobody writes as a Hebrew
// word. Loanwords with an accepted Hebrew spelling (אובייקט, פונקציה, מודל,
// אינדקס) and transliterations that collide with real Hebrew words (פול the
// bean, פורק the verb, הלם, של, מיין) are left out on purpose — the Dictionary
// is conservative by design (SM-C2), and a user who wants them adds them once.

import Foundation

enum DeveloperTerms {

    /// Set once the pack has been offered to a fresh install, so it is never
    /// re-added behind the user's back after they delete entries from it.
    static let seededDefaultsKey = "vocamac.dictionary.developerTermsSeeded"

    /// Adds the pack to an empty Dictionary exactly once per install. A
    /// Dictionary that already has entries belongs to someone who set it up
    /// before this pack existed; they get the button in Settings instead.
    @MainActor
    static func seedIfFresh(into store: DictionaryStore, defaults: UserDefaults = VocaDefaults.store) {
        guard !defaults.bool(forKey: seededDefaultsKey) else { return }
        defaults.set(true, forKey: seededDefaultsKey)
        guard store.entries.isEmpty else { return }
        store.merge(hebrewToEnglish)
    }

    private static func t(_ canonical: String, _ triggers: String...) -> DictionaryEntry {
        DictionaryEntry(canonicalForm: canonical, triggers: triggers)
    }

    static let hebrewToEnglish: [DictionaryEntry] = [
        // MARK: Git and code review
        t("commit", "קומיט", "קומית"),
        t("commits", "קומיטים"),
        t("push", "פוש"),
        t("pull request", "פול ריקווסט", "פול ריקוואסט", "פול ריקווסטים"),
        t("PR", "פי אר"),
        t("merge", "מרג'", "מרג׳", "מרג"),
        t("merge conflict", "מרג קונפליקט"),
        t("rebase", "ריבייס"),
        t("branch", "ברנץ'", "ברנץ", "ברנצ'"),
        t("branches", "ברנצ'ים", "ברנצים"),
        t("checkout", "צ'קאאוט", "צקאאוט", "צ'ק אאוט"),
        t("clone", "קלון"),
        t("stash", "סטאש"),
        t("tag", "טאג"),
        t("tags", "טאגים"),
        t("diff", "דיף"),
        t("revert", "ריוורט"),
        t("cherry-pick", "צ'רי פיק"),
        t("squash", "סקוואש"),
        t("origin", "אוריג'ין"),
        t("upstream", "אפסטרים"),
        t("remote", "רימוט"),
        t("repo", "ריפו"),
        t("repository", "ריפוזיטורי"),
        t("git", "גיט"),
        t("GitHub", "גיטהאב", "גיט האב"),
        t("GitLab", "גיטלאב"),
        t("Bitbucket", "ביטבאקט"),
        t("code review", "קוד ריוויו"),
        t("release", "רילים", "ריליס"),
        t("changelog", "צ'יינג'לוג"),
        t("hotfix", "הוטפיקס"),
        t("patch", "פאץ'", "פאץ"),

        // MARK: Building, testing, shipping
        t("bug", "באג"),
        t("bugs", "באגים"),
        t("debug", "דיבאג"),
        t("debugger", "דיבאגר"),
        t("build", "בילד"),
        t("deploy", "דיפלוי"),
        t("deployment", "דיפלוימנט"),
        t("rollback", "רולבק"),
        t("refactor", "ריפקטור", "ריפאקטור"),
        t("test", "טסט"),
        t("tests", "טסטים"),
        t("unit test", "יוניט טסט"),
        t("unit tests", "יוניט טסטים"),
        t("e2e", "אי טו אי"),
        t("mock", "מוק"),
        t("linter", "לינטר"),
        t("lint", "לינט"),
        t("compile", "קומפייל"),
        t("compiler", "קומפיילר"),
        t("runtime", "ראנטיים"),
        t("stack trace", "סטאק טרייס"),
        t("exception", "אקספשן"),
        t("crash", "קראש"),
        t("timeout", "טיימאאוט"),
        t("latency", "לייטנסי"),
        t("performance", "פרפורמנס"),
        t("benchmark", "בנצ'מארק"),
        t("log", "לוג"),
        t("logs", "לוגים"),
        t("logging", "לוגינג"),
        t("config", "קונפיג"),
        t("environment", "אנוויירונמנט", "אנווירונמנט"),
        t("production", "פרודקשן", "פרודקשיין"),
        t("prod", "פרוד"),
        t("staging", "סטייג'ינג"),
        t("localhost", "לוקלהוסט", "לוקאלהוסט"),
        t("CI", "סי איי"),
        t("CI/CD", "סי איי סי די"),
        t("pipeline", "פייפליין"),
        t("GitHub Actions", "גיטהאב אקשנס"),
        t("workflow", "וורקפלואו", "וורקפלו"),
        t("artifact", "ארטיפקט"),
        t("Jenkins", "ג'נקינס"),

        // MARK: Architecture and APIs
        t("frontend", "פרונטאנד", "פרונט אנד"),
        t("backend", "בקאנד", "בק אנד"),
        t("full-stack", "פולסטאק", "פול סטאק"),
        t("API", "איי פי איי", "אי פי איי"),
        t("endpoint", "אנדפוינט"),
        t("endpoints", "אנדפוינטים"),
        t("request", "ריקווסט"),
        t("response", "ריספונס"),
        t("payload", "פיילואד"),
        t("header", "הדר"),
        t("headers", "הדרים"),
        t("status code", "סטטוס קוד"),
        t("webhook", "ווב הוק", "ובהוק", "וובהוק"),
        t("WebSocket", "ווב סוקט", "וובסוקט"),
        t("REST", "רסט"),
        t("GraphQL", "גרף קיו אל", "גראפ קיו אל"),
        t("JSON", "ג'ייסון", "ג'ייסן"),
        t("YAML", "יאמל"),
        t("XML", "אקס אם אל"),
        t("CSV", "סי אס וי"),
        t("Markdown", "מרקדאון"),
        t("README", "רידמי"),
        t("token", "טוקן"),
        t("tokens", "טוקנים"),
        t("authentication", "אותנטיקציה"),
        t("authorization", "אוטוריזציה"),
        t("login", "לוגין"),
        t("logout", "לוגאאוט"),
        t("session", "סשן"),
        t("cookie", "קוקי"),
        t("cache", "קאש"),
        t("cron", "קרון"),
        t("job", "ג'וב"),
        t("queue", "קיו"),
        t("worker", "וורקר"),
        t("thread", "ת'רד"),
        t("process", "פרוסס"),
        t("service", "סרוויס"),
        t("microservice", "מיקרוסרוויס"),
        t("microservices", "מיקרוסרוויסים"),
        t("monolith", "מונולית"),
        t("server", "סרבר"),
        t("client", "קליינט"),
        t("middleware", "מידלוור"),
        t("router", "ראוטר"),
        t("route", "ראוט"),
        t("controller", "קונטרולר"),
        t("SDK", "אס די קיי"),
        t("CLI", "סי אל איי"),
        t("plugin", "פלאגין"),
        t("plugins", "פלאגינים"),
        t("extension", "אקסטנשן"),

        // MARK: Data
        t("database", "דאטאבייס", "דאטהבייס", "דטאבייס"),
        t("DB", "די בי"),
        t("query", "קווארי", "קוורי"),
        t("SQL", "אס קיו אל", "סיקוול"),
        t("Postgres", "פוסטגרס"),
        t("MySQL", "מיי אס קיו אל"),
        t("MongoDB", "מונגו", "מונגו די בי"),
        t("Redis", "רדיס"),
        t("Elasticsearch", "אלסטיק סרץ'", "אלסטיקסרץ'"),
        t("Kafka", "קפקא"),
        t("S3", "אס שלוש", "אס תרי"),
        t("bucket", "באקט"),
        t("Supabase", "סופאבייס", "סופהבייס"),
        t("Firebase", "פיירבייס"),
        t("Prisma", "פריזמה או אר אם"),

        // MARK: Infrastructure and cloud
        t("Docker", "דוקר"),
        t("container", "קונטיינר"),
        t("containers", "קונטיינרים"),
        t("image", "אימג'"),
        t("Kubernetes", "קוברנטיס", "קוברנטס"),
        t("pod", "פוד"),
        t("cluster", "קלאסטר"),
        t("Terraform", "טרהפורם", "טראפורם"),
        t("nginx", "אנג'ינקס"),
        t("proxy", "פרוקסי"),
        t("load balancer", "לואד באלנסר"),
        t("firewall", "פיירוול"),
        t("VPN", "וי פי אן"),
        t("DNS", "די אן אס"),
        t("domain", "דומיין"),
        t("SSL", "אס אס אל"),
        t("certificate", "סרטיפיקט"),
        t("port", "פורט"),
        t("host", "הוסט"),
        t("IP", "איי פי"),
        t("SSH", "אס אס אייץ'"),
        t("serverless", "סרברלס"),
        t("Lambda", "למבדה"),
        t("AWS", "איי דאבליו אס"),
        t("Azure", "אז'ור"),
        t("GCP", "ג'י סי פי"),
        t("Cloudflare", "קלאודפלייר"),
        t("Vercel", "ורסל", "וורסל"),
        t("Netlify", "נטליפיי"),
        t("Heroku", "הרוקו"),
        t("Linux", "לינוקס"),
        t("Ubuntu", "אובונטו"),
        t("macOS", "מק או אס"),
        t("iOS", "איי או אס"),
        t("Windows", "ווינדוס"),

        // MARK: Terminal and packages
        t("terminal", "טרמינל"),
        t("bash", "באש"),
        t("script", "סקריפט"),
        t("scripts", "סקריפטים"),
        t("command", "קומנד"),
        t("flag", "פלאג"),
        t("argument", "ארגומנט"),
        t("path", "פאת'"),
        t("folder", "פולדר"),
        t("directory", "דירקטורי"),
        t("package", "פאקג'", "פקג'"),
        t("packages", "פאקג'ים"),
        t("dependency", "דיפנדנסי"),
        t("dependencies", "דיפנדנסיז", "דיפנדנסיס"),
        t("install", "אינסטול"),
        t("npm", "אן פי אם"),
        t("yarn", "יארן"),
        t("pip", "פיפ"),
        t("Homebrew", "הומברו"),
        t("library", "לייבררי", "ליברי"),
        t("framework", "פריימוורק"),

        // MARK: Languages and frameworks
        t("TypeScript", "טייפסקריפט"),
        t("JavaScript", "ג'אווהסקריפט", "ג'אבהסקריפט"),
        t("Python", "פייתון"),
        t("Java", "ג'אווה"),
        t("Swift", "סוויפט"),
        t("SwiftUI", "סוויפט יו איי"),
        t("Kotlin", "קוטלין"),
        t("Rust", "ראסט"),
        t("C#", "סי שארפ"),
        t(".NET", "דוט נט"),
        t("Node.js", "נוד ג'י אס"),
        t("React", "ריאקט"),
        t("Next.js", "נקסט ג'י אס"),
        t("Angular", "אנגולר"),
        t("Express", "אקספרס ג'י אס"),
        t("Tailwind", "טיילווינד"),
        t("Redux", "רידאקס"),
        t("Webpack", "וובפאק"),
        t("ESLint", "אי אס לינט"),
        t("Prettier", "פריטייר"),
        t("Jest", "ג'סט"),
        t("Cypress", "סייפרס"),
        t("Storybook", "סטוריבוק"),
        t("Swagger", "סווגר"),
        t("Postman", "פוסטמן"),

        // MARK: Code vocabulary
        t("function", "פאנקשן"),
        t("variable", "וריאבל"),
        t("array", "אריי"),
        t("string", "סטרינג"),
        t("boolean", "בוליאן"),
        t("integer", "אינטג'ר"),
        t("null", "נאל"),
        t("undefined", "אנדיפיינד"),
        t("interface", "אינטרפייס"),
        t("enum", "אינאם", "אנום"),
        t("struct", "סטראקט"),
        t("loop", "לופ"),
        t("callback", "קולבק"),
        t("promise", "פרומיס"),
        t("async", "אסינק"),
        t("await", "אווייט"),
        t("return", "ריטרן"),
        t("import", "אימפורט"),
        t("export", "אקספורט"),
        t("default", "דיפולט"),
        t("type", "טייפ"),
        t("generic", "ג'נריק"),
        t("pointer", "פוינטר"),
        t("memory leak", "מאמורי ליק", "ממורי ליק"),
        t("regex", "רג'קס"),
        t("parser", "פארסר"),
        t("hash", "האש"),
        t("UUID", "יו יו איי די"),
        t("ID", "איי די"),
        t("value", "ואליו"),
        t("list", "ליסט"),
        t("stack", "סטאק"),
        t("template", "טמפלייט"),
        t("layout", "לייאאוט"),
        t("grid", "גריד"),
        t("flex", "פלקס"),
        t("responsive", "רספונסיבי"),
        t("breakpoint", "ברייקפוינט"),
        t("viewport", "ויופורט"),
        t("scroll", "סקרול"),
        t("hover", "הובר"),
        t("modal", "מודאל"),
        t("popup", "פופאפ"),
        t("tooltip", "טולטיפ"),
        t("dropdown", "דרופדאון"),
        t("sidebar", "סיידבר"),
        t("navbar", "נאבבר"),
        t("footer", "פוטר"),
        t("input", "אינפוט"),
        t("checkbox", "צ'קבוקס"),
        t("toggle", "טוגל"),
        t("slider", "סליידר"),
        t("placeholder", "פלייסהולדר"),
        t("dark mode", "דארק מוד"),
        t("component", "קומפוננטה", "קומפוננט"),
        t("components", "קומפוננטות", "קומפוננטים"),
        t("props", "פרופס"),
        t("state", "סטייט"),
        t("hook", "הוק"),
        t("hooks", "הוקס", "הוקים"),
        t("render", "רנדר"),
        t("CSS", "סי אס אס"),
        t("HTML", "אייץ טי אם אל", "אצ טי אם אל"),

        // MARK: AI tooling
        t("Claude", "קלוד"),
        t("Claude Code", "קלוד קוד"),
        t("CLAUDE.md", "קלוד אמדי", "קלוד אם די", "קלוד אמ די"),
        t("Anthropic", "אנתרופיק"),
        t("ChatGPT", "צ'אט ג'יפיטי", "צאט ג'יפיטי", "צ'אט גיפיטי"),
        t("GPT", "ג'יפיטי"),
        t("OpenAI", "אופן איי איי"),
        t("Codex", "קודקס"),
        t("Gemini", "ג'מיני"),
        t("Copilot", "קופיילוט"),
        t("Cursor", "קרסר"),
        t("VS Code", "וי אס קוד"),
        t("Xcode", "אקסקוד"),
        t("LLM", "אל אל אם"),
        t("prompt", "פרומפט"),
        t("prompts", "פרומפטים"),
        t("agent", "אייג'נט"),
        t("agents", "אייג'נטים"),
        t("subagent", "סאבאייג'נט"),
        t("MCP", "אם סי פי"),
        t("RAG", "ראג"),
        t("embedding", "אמבדינג"),
        t("embeddings", "אמבדינגס"),
        t("fine-tuning", "פיין טיונינג"),
        t("inference", "אינפרנס"),
        t("Whisper", "וויספר"),
        t("Ollama", "אולמה"),
        t("LM Studio", "אל אם סטודיו"),
        t("Hugging Face", "האגינג פייס"),

        // MARK: Product and process
        t("sprint", "ספרינט"),
        t("backlog", "בקלוג"),
        t("standup", "סטנדאפ"),
        t("retro", "רטרו"),
        t("scrum", "סקראם"),
        t("agile", "אג'ייל"),
        t("kanban", "קנבן"),
        t("roadmap", "רודמאפ"),
        t("MVP", "אם וי פי"),
        t("POC", "פי או סי"),
        t("feature", "פיצ'ר"),
        t("features", "פיצ'רים"),
        t("issue", "אישיו"),
        t("ticket", "טיקט"),
        t("epic", "אפיק"),
        t("deadline", "דדליין"),
        t("milestone", "מיילסטון"),
        t("stakeholder", "סטייקהולדר"),
        t("KPI", "קיי פי איי"),
        t("onboarding", "אונבורדינג"),
        t("UX", "יו אקס"),
        t("UI", "יו איי"),
        t("wireframe", "וויירפריים"),
        t("mockup", "מוקאפ"),
        t("dashboard", "דשבורד"),
        t("admin", "אדמין"),
        t("user", "יוזר"),
        t("users", "יוזרים"),
        t("startup", "סטארטאפ"),
        t("demo", "דמו"),
        t("beta", "בטא"),
        t("Slack", "סלאק"),
        t("Discord", "דיסקורד"),
        t("Notion", "נושן"),
        t("Jira", "ג'ירה"),
        t("Confluence", "קונפלואנס"),
        t("Trello", "טרלו"),
        t("Figma", "פיגמה"),
        t("Teams", "טימס"),
        t("Sentry", "סנטרי"),
        t("Datadog", "דאטהדוג"),
        t("Grafana", "גרפנה"),
        t("Prometheus", "פרומתאוס"),
        t("Stripe", "סטרייפ"),
    ]
}
